export default {
    BEGIN_AJAX_CALL: 'BEGIN_AJAX_CALL',
    END_AJAX_CALL: 'END_AJAX_CALL',
    AJAX_CALL_ERROR: 'AJAX_CALL_ERROR',
    SET_REDIRECT_URL: 'SET_REDIRECT_URL',
    BEGIN_INTERNAL_LOADING: 'BEGIN_INTERNAL_LOADING',
    END_INTERNAL_LOADING: 'END_INTERNAL_LOADING'
};
